title: Catálogo de Camisetas
description: "Catálogo de camisetas personalizadas"
theme: minimal-mistakes-jekyll
url: "https://indalfut.github.io"
repository: indalfut/indalfut.github.io

# Tema y skin (ver opciones aquí: https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#skin-settings)
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"  # "air", "aqua", "dark", "dirt", "neon", "mint"

# Plugins necesarios
plugins:
  - jekyll-include-cache
  - jekyll-feed

# Opcional: Configuración por defecto para páginas
defaults:
  - scope:
      path: ""
    values:
      layout: "single"