- name: "Camiseta Clásica"
  price: "$19.99"
  image: "camiseta1.jpg"
  description: "100% algodón, disponible en varios colores."

- name: "Camiseta Estampada"
  price: "$24.99"
  image: "camiseta2.jpg"
  description: "Diseño exclusivo con estampado artístico."