- name: "Camiseta Clásica"
  price: "$19.99"
  image: "camiseta1.jpg"
  description: "100% algodón, colores variados."

- name: "Camiseta Premium"
  price: "$24.99"
  image: "camiseta2.jpg"
  description: "Estampado de alta calidad."